### ISSUE TITLE
Latest update breaks youtube.com

### ISSUE THREAD

**Issue by zeroliu** [apollographql/apollo-client-devtools#455]
**Intended outcome:**

youtube.com loads successfully.

**Actual outcome:**

youtube.com scripts failed to load when the apollo extension is turn on, with the error:
`Uncaught TypeError: Cannot assign to read only property 'process' of object '#<Window>'`
It seems that the apollo extension sets the window.process to a readonly property and the youtube script tries to set it again.

**How to reproduce the issue:**

- Install the apollo chrome extension
- Go to youtube.com

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Browser version [e.g. 22] 89
 - Extension version [e.g. 3.0] 3.0.0

**Comment by webjoyable** [comment]
Same here,

**Extension version:** 3.0.0
**OS:** Windows 10 64bit,
**Browser:** Chrome v89.0.4389.90

**Comment by JonathanEkberg** [comment]
Having the same issue

**Extension version:** 3.0.0
**OS:** Windows 10 OS Version 2009 (Build 19042.867)
**Browser:** Edge 89.0.774.54 (Official build) (64-bit)

**Comment by timhere** [comment]
I'm also experiencing this issue, refreshing the page seems to get past the initial error. Hard refresh causes it to appear again.

**Extension version:** 3.0.0
**OS:** Arch linux 5.11.6-arch1-1
**Browser:** Chromium 89.0.4389.90

**Comment by hwillson** [comment]
Yikes - I'll take a look. Thanks all!

**Comment by hwillson** [comment]
The culprit seems to be Apollo Client's `ts-invariant` dependency, which is locking `process`: https://github.com/apollographql/invariant-packages/blob/68796f8a7c3d36338402ff1280dd9dfff38db521/packages/ts-invariant/src/invariant.ts

We're working on a fix.

**Comment by derwaldgeist** [comment]
Same problem here. It also broke my Meteor app (but only since the latest Chrome update).

**Comment by hwillson** [comment]
Fixed in https://github.com/apollographql/apollo-client-devtools/pull/460, but re-opening until the new version if published.

**Comment by hwillson** [comment]
Apollo Client Devtools 3.0.1 has been submitted for review; 🤞it will be available shortly.

**Comment by hwillson** [comment]
3.0.1 should be available now - let me know if this issue still occurs. Thanks!

**Comment by claytonmarinho** [comment]
> 3.0.1 should be available now - let me know if this issue still occurs. Thanks!

Hi, I got installed Apollo Client Devtools 3.0.1 but I still facing the issue.
Chrome 89.0.4389.90
