### ISSUE TITLE
Latest update breaks Asana.com

### ISSUE THREAD

**Issue by ggravlingen** [apollographql/apollo-client-devtools#457]
**Intended outcome:**
I'm trying to visit an organisation in Asana.com.

**Actual outcome:**
The Asana dashboard does not load. The loading spinner keeps circulating between different Asana assets that are loaded (projects, inbox etc). When disabling the Apollo Chrome extension, the page loads. I can also access the page when re-enabling the extension.

**How to reproduce the issue:**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Browser version Version 89.0.4389.82 (Official Build) (64-bit)
 - Extension version 3.0.0

Possibly related to #455?

**Comment by ggravlingen** [comment]
Some console output:
```
[2021-03-15T15:47:18.240Z] Created early WebSocket with PageLoad shard specification
bundle.js:2 Uncaught TypeError: Cannot set property 'exports' of undefined
    at Object.<anonymous> (bundle.js:2)
    at Object.page_load_bundle_evaluation_failure_checker (bundle.js:2)
    at o (bundle.js:2)
    at Object.page_load_bundle_evaluation_failure_checker (bundle.js:2)
    at o (bundle.js:2)
    at bundle.js:2
    at bundle.js:2
start_session?path=%2F0%2Fhome%2F1199901208724637&query_string=&rparam=01807108763015184487&user_id=1199901208708726&shard_id=1199901271604579&t=1615823238124&k=key_one&h=ac8cf49c52453f9be9f57cc35ef2eb190b1d46fa5b5672566cd2e7823dddde71&release_revision=20210311_181458_b09cbd9598bedb2b021fbe939c388a2a1f8accd2&sync_cluster=prod:1 Uncaught ReferenceError: Deserializer is not defined
    at start_session:1
    at start_session:1
```

**Comment by HeyParkerJ** [comment]
Latest update also broke TargetProcess for people in my organization.

**Comment by hwillson** [comment]
Fixed in https://github.com/apollographql/apollo-client-devtools/pull/460, but re-opening until the new version is published.

**Comment by hwillson** [comment]
Apollo Client Devtools 3.0.1 has been submitted for review; 🤞it will be available shortly.

**Comment by hwillson** [comment]
3.0.1 should be available now - let me know if this issue still occurs. Thanks!

**Comment by ggravlingen** [comment]
Thanks for looking into this! I'm on 3.0.1 now and unfortunately, the error still persists. Same error in console as yesterday. Is there any more data I can retrieve on my end in order to help?

![image](https://user-images.githubusercontent.com/21142447/111264939-ab8eac00-8628-11eb-82b1-1437d73ec855.png)

**Comment by jfirebaugh** [comment]
Same here, on version 3.0.1 and I couldn't use Asana until I disabled the extension.

**Comment by hwillson** [comment]
3.0.2 has been submitted for review with a fix for this - thanks!

**Comment by hwillson** [comment]
3.0.2 has been published and this issue appears to be fixed. Let us know otherwise. Thanks!

**Comment by ggravlingen** [comment]
Just confirming that it works on 3.0.2. Thanks for your help!

**Comment by hwillson** [comment]
Phew - thanks @ggravlingen and sorry about that!
