### ISSUE TITLE
GraphiQL results show `[object Object]` for errors without data with AC 2.0

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-client-devtools#81]
I just upgraded to AC 2.0 and devtools 2.0.5.  When I run a query, I get `[object Object]` as the response instead of JSON.

![image](https://user-images.githubusercontent.com/16724/32012615-48226c5a-b96d-11e7-8a92-e79e131d21f0.png)

**Comment by glasser** [comment]
Ah, this seems to specifically happen with certain kinds of errors, like unknown fields. So this query

```
query {
  xxx
}
```

triggers the issue.

**Comment by glasser** [comment]
Looks like the difference between this kind of response which looks good:

```
{"data":{"app":null},"errors":[{"message":"Requested resource was not found [not-found]","locations":[{"line":1,"column":2}],"path":["app"]}]}
```

and this which doesn't

```
{"errors":[{"message":"Cannot query field \"xxx\" on type \"RootQuery\".","locations":[{"line":1,"column":12}]}]}
```

**Comment by glasser** [comment]
May also be the difference between a 200 response and a 400 response.

**Comment by glasser** [comment]
Confirmed that it definitely works with AC 1.0.

**Comment by glasser** [comment]
OK, this issue needs to be fixed in apollo-link-http, not just in the devtools.  It's because of [this code](https://github.com/apollographql/apollo-link/blob/cdb2a5ec2629cef1c56f96eab226c38528aff846/packages/apollo-link-http/src/httpLink.ts#L21-L24) which doesn't appear to have an equivalent in the 1.0 createNetworkInterface.

[`apollo-server` turns any response with `error` and no `data` into a 400](https://github.com/apollographql/apollo-server/blob/c9b8ef9d2495f2088c2e1c51c7f1f6234abaca97/packages/apollo-server-core/src/runHttpQuery.ts#L144-L148) and `apollo-link-http` turns that into an error which doesn't actually have the JSON on it.  (It does put the response on the error, but the JSON was already read so you can't re-read it from the response.)

It also misleadingly puts an error on a field called `parseError` even when it doesn't have to be a parse error.

**Comment by glasser** [comment]
Filed apollographql/apollo-link#178 for the underlying issue.

**Comment by glasser** [comment]
@evans Now that the apollo-link issue is fixed, can you check to see if this is fixed?

**Comment by KeithGillette** [comment]
This issue still occurs with Apollo Client Developer Tools 2.0.6 and `apollo-link@1.0.7` for responses with an `error` but not a `data` property.

**Comment by jbaxleyiii** [comment]
This is fixed in the newest build!

**Comment by wawhal** [comment]
This still happens with `apollo-link-ws`.

**Comment by almostprogrammer** [comment]
I've also observed this behaviour in `apollo-link-http` when used in `graphql-bindings`

**Comment by PaulRBerg** [comment]
Using `apollo-link-ws@1.0.19` and `apollo-client-devtools@2.2.5` and this issue still exists.
.

**Comment by zenVentzi** [comment]
```
"@apollo/react-hooks": "^3.1.3",
    "@apollo/react-ssr": "^3.1.3",
 "apollo-cache-inmemory": "^1.6.5",
    "apollo-client": "^2.6.8",
    "apollo-link": "^1.2.13",
    "apollo-link-context": "^1.0.19",
    "apollo-link-error": "^1.1.12",
    "apollo-link-http": "^1.5.16",
```
![image](https://user-images.githubusercontent.com/11378653/76159187-7488df00-6126-11ea-9d86-31efdd1a6d69.png)

Actual response taken from the Network tab:
```
{"errors":[{"message":"Context creation failed: Invalid scheme ","extensions":{"code":"UNAUTHENTICATED","exception":{"stacktrace":["AuthenticationError: Context creation failed: Invalid scheme ","    at ApolloServer.context (/mnt/c/Users/zen_ventzi/Documents/s.engineering/devbeat/qnary-api/src/index.ts:133:15)","    at ApolloServer.<anonymous> (/mnt/c/Users/zen_ventzi/Documents/s.engineering/devbeat/qnary-api/node_modules/apollo-server-core/src/ApolloServer.ts:737:24)","    at Generator.next (<anonymous>)","    at fulfilled (/mnt/c/Users/zen_ventzi/Documents/s.engineering/devbeat/qnary-api/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}}}]}
```

**Comment by mattgabor** [comment]
Seeing this with:
```
    "@apollo/client": "3.0.0-rc.12",
    "@apollo/react-hooks": "3.1.3"
```
